name: 'Setup Android Environment'
description: 'Sets up Java 17, Android SDK, and decodes the keystore'

inputs:
  keystore-b64:
    description: 'Base64 encoded keystore string'
    required: true
  keystore-password:
    description: 'Password for the release keystore'
    required: true
  keystore-alias:
    description: 'Alias for the release key'
    required: true
  key-password:
    description: 'Password for the release key'
    required: true

runs:
  using: "composite"
  steps:
    - name: Setup Java
      uses: actions/setup-java@v6
      with:
        distribution: 'temurin'
        java-version: 17

    - name: Setup Android SDK
      uses: android-actions/setup-android@v4.0.1

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v6

    - name: Grant execute permission for gradlew
      shell: bash
      run: chmod +x gradlew

    - name: Decode Keystore
      shell: bash
      env:
        ENCODED_STRING: ${{ inputs.keystore-b64 }}
        RELEASE_KEYSTORE_PASSWORD: ${{ inputs.keystore-password }}
        RELEASE_KEYSTORE_ALIAS: ${{ inputs.keystore-alias }}
        RELEASE_KEY_PASSWORD: ${{ inputs.key-password }}
      run: |
        echo $ENCODED_STRING > keystore-b64.txt
        base64 -d keystore-b64.txt > keystore.jks
        echo "keystorePassword=$RELEASE_KEYSTORE_PASSWORD" > local.properties
        echo "keyAlias=$RELEASE_KEYSTORE_ALIAS" >> local.properties
        echo "keyPassword=$RELEASE_KEY_PASSWORD" >> local.properties
