name: Dependency Submission

on:
  push:
    branches: [ "master" ]

permissions:
  contents: write

jobs:
  dependency-submission:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Setup Shared Android Environment
        uses: ./.github/actions/setup-android-env
        with:
          keystore-b64: ${{ secrets.KEYSTORE_BASE_64 }}
          keystore-password: ${{ secrets.RELEASE_KEYSTORE_PASSWORD }}
          keystore-alias: ${{ secrets.RELEASE_KEYSTORE_ALIAS }}
          key-password: ${{ secrets.RELEASE_KEY_PASSWORD }}

      - name: Submit Dependencies
        uses: gradle/actions/dependency-submission@v6
